Repository BonaDrone/Hackflight, pull requests merged in 2019-03, with the labels that each got.

#70 Transmitter calibration
  CHANGES.md
  extras/parser/messages.json
  extras/parser/resources/mspparser.hpp
  src/datatypes.hpp
  src/hackflight.hpp
  src/main.hpp
  src/mspparser.hpp
  src/receiver.hpp
  src/receivers/sbus.hpp
Labels: enhancement, next release

#73 Battery Monitoring
  CHANGES.md
  extras/parser/messages.json
  src/boards/bonadrone.hpp
  src/datatypes.hpp
  src/hackflight.hpp
  src/mspparser.hpp
Labels: enhancement, next release

#76 Controller refactor
  CHANGES.md
  examples/Bonadrone/SBUSLevel/SBUSLevel.ino
  src/boards/bonadrone.hpp
  src/pidcontrollers/level.hpp
  src/pidcontrollers/rate.hpp
Labels: enhancement, next release

#75 Filter integration
  CHANGES.md
  examples/Bonadrone/SBUSLevel/SBUSLevel.ino
  extras/parser/messages.json
  extras/parser/resources/mspparser.hpp
  src/board.hpp
  src/boards/bonadrone.hpp
  src/boards/softquat.hpp
  src/datatypes.hpp
  src/filters/eskf.hpp
  src/filters/eskf_sensor.hpp
  src/filters/eskf_struct.hpp
  src/filters/linalg.hpp
  src/hackflight.hpp
  src/main.hpp
  src/mspparser.hpp
  src/pidcontroller.hpp
  src/pidcontrollers/althold.hpp
  src/pidcontrollers/level.hpp
  src/pidcontrollers/poshold.hpp
  src/pidcontrollers/rate.hpp
  src/pidcontrollers/setpoint.hpp
  src/planner.hpp
  src/receiver.hpp
  src/receivers/sbus.hpp
  src/sensor.hpp
  src/sensors/accelerometer.hpp
  src/sensors/barometer.hpp
  src/sensors/gyrometer.hpp
  src/sensors/imu.hpp
  src/sensors/magnetometer.hpp
  src/sensors/opticalflow.hpp
  src/sensors/peripheral.hpp
  src/sensors/quaternion.hpp
  src/sensors/rangefinder.hpp
  src/sensors/surfacemount.hpp
Labels: enhancement, next release

#77 Fix Optical Flow correction in ESKF
  CHANGES.md
  src/main.hpp
  src/sensors/opticalflow.hpp
Labels: bug

#79 Added Get/Set MSP methods to manage PID constants
  CHANGES.md
  extras/parser/messages.json
  src/hackflight.hpp
  src/mspparser.hpp
Labels: enhancement, next release

#80 Enable clearing EEPROM by sections
  CHANGES.md
  extras/parser/messages.json
  src/hackflight.hpp
  src/mspparser.hpp
Labels: enhancement

#95 Flight mission completed MSP check
  CHANGES.md
  extras/parser/messages.json
  src/hackflight.hpp
  src/mspparser.hpp
Labels: enhancement, next release

#96 Emergency stop via MSP
  CHANGES.md
  extras/parser/messages.json
  src/hackflight.hpp
  src/mspparser.hpp
Labels: enhancement, next release, to be tested

#102 Tune and refactor ESKF
  CHANGES.md
  src/filters/eskf.hpp
  src/hackflight.hpp
  src/sensors/imu.hpp
  src/sensors/opticalflow.hpp
Labels: enhancement, next release

#103 Allow to specify MSP messages that do not acknowledge
  CHANGES.md
  extras/parser/msppg.py
  src/mspparser.hpp
Labels: enhancement, next release

#105 Filter ESKF estimated linear velocities with a LPF (+tuning)
  CHANGES.md
  src/filters/eskf.hpp
  src/sensors/imu.hpp
  src/sensors/opticalflow.hpp
Labels: enhancement, next release

#107 Main loop improvements
  CHANGES.md
  examples/Bonadrone/Parametrized/Parametrized.ino
  src/main.hpp
Labels: enhancement, next release
